# Generated by Django 3.1.6 on 2021-02-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('team_availability', models.CharField(max_length=128, null=True)),
                ('response_times', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(max_length=128, null=True)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('profile_image', models.CharField(max_length=128, null=True)),
                ('manager', models.CharField(max_length=128, null=True)),
                ('battery_level', models.DecimalField(decimal_places=5, max_digits=5)),
                ('preferred_hours', models.CharField(max_length=128, null=True)),
                ('goals_personal', models.CharField(max_length=1024, null=True)),
                ('goals_professional', models.CharField(max_length=1024, null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamflow.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
