# Generated by Django 3.1.6 on 2021-02-13 21:58

from django.db import migrations

def create_data(apps, schema_editor):
    Team = apps.get_model('teamflow', 'Team')
    Team(team_name="Pilot Team", team_availability="Workin' 9 to 5", response_times="asap").save()


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
